[tool.ruff]
exclude = [".venv"]
line-length = 88

[tool.ruff.lint]
select = ['ALL']
ignore = ["D", "E501", "TD", "FIX", "BLE001"]

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true